//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {


    public struct Hello {

        /// Base translation: hello
        public static var Surname : String = NSLocalizedString("Hello.surname", comment: "")

        /// Base translation: hello2
        public static var Name : String = NSLocalizedString("Hello.name", comment: "")

    }
}